name: task_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.4
  ionicons: 0.1.2
  firebase_core: 1.19.2
  firebase_auth: 3.4.2
  google_sign_in: 5.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
